/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.fasterxml.jackson.core.type.TypeReference;
import com.lob.api.ApiHelper;
import com.lob.api.LobClient;
import com.lob.api.exceptions.ApiException;
import com.lob.api.models.AllTemplates;
import com.lob.api.models.BeforeAfter;
import com.lob.api.models.EngineEnum;
import com.lob.api.models.Template;
import io.apimatic.core.utilities.TestHelper;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class TemplatesControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static LobClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static TemplatesController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getTemplatesController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Returns a list of your templates. The templates are returned sorted by creation date, with
     * the most recently created templates appearing first.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestTemplatesList() throws Exception {
        // Parameters for the API call
        Integer limit = 10;
        BeforeAfter beforeAfter = null;
        List<String> include = null;
        Map<String, String> dateCreated = null;
        Map<String, String> metadata = null;

        // Set callback and perform API call
        AllTemplates result = null;
        try {
            result = controller.templatesList(limit, beforeAfter, include, dateCreated, metadata);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertTrue("Response body does not match in keys", 
                TestHelper.isJsonObjectProperSubsetOf(
                "{\"data\":[{\"id\":\"tmpl_d5a5a89da9106f8\",\"description\":\"Test Template\",\"ve"
                + "rsions\":[{\"id\":\"vrsn_232a02fb8224791\",\"suggest_json_editor\":true,\"descri"
                + "ption\":\"Test Template\",\"engine\":\"legacy\",\"html\":\"HTML for \",\"date_cr"
                + "eated\":\"2019-07-27T23:49:01.512Z\",\"date_modified\":\"2019-07-27T23:49:01.512"
                + "Z\",\"object\":\"version\"}],\"published_version\":{\"id\":\"vrsn_232a02fb822479"
                + "1\",\"suggest_json_editor\":false,\"description\":\"Test Template\",\"engine\":"
                + "\"handlebars\",\"html\":\"HTML for \",\"date_created\":\"2019-07-27T23:49:01.512"
                + "Z\",\"date_modified\":\"2019-07-27T23:49:01.512Z\",\"object\":\"version\"},\"met"
                + "adata\":{},\"date_created\":\"2019-07-27T23:49:01.511Z\",\"date_modified\":\"201"
                + "9-07-27T23:49:01.511Z\",\"object\":\"template\"},{\"id\":\"tmpl_59b2150ae120887"
                + "\",\"description\":\"Test Template\",\"versions\":[{\"id\":\"vrsn_2a7eb63ccb795b"
                + "9\",\"description\":\"Test Template\",\"html\":\"HTML for \",\"date_created\":"
                + "\"2019-03-29T10:22:34.643Z\",\"date_modified\":\"2019-03-29T10:22:34.643Z\",\"ob"
                + "ject\":\"version\"}],\"published_version\":{\"id\":\"vrsn_2a7eb63ccb795b9\",\"de"
                + "scription\":\"Test Template\",\"html\":\"HTML for \",\"date_created\":\"2019-03-"
                + "29T10:22:34.643Z\",\"date_modified\":\"2019-03-29T10:22:34.643Z\",\"object\":\"v"
                + "ersion\"},\"metadata\":{},\"date_created\":\"2019-03-29T10:22:34.642Z\",\"date_m"
                + "odified\":\"2019-03-29T10:22:34.642Z\",\"object\":\"template\"}],\"object\":\"li"
                + "st\",\"previous_url\":null,\"next_url\":\"https://api.lob.com/v1/templates?limit"
                + "=2&after=eyJkYXRlT2Zmc2V0IjoiMjAxOS0wMy0yOVQxMDoyMjozNC42NDJaIiwiaWRPZmZzZXQiOiJ"
                + "0bXBsXzU5YjIxNTBhZTEyMDg4NyJ9\",\"count\":2}",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()), 
                false, true, false));
    }

    /**
     * Creates a new template for use with the Print &amp; Mail API. In Live mode, you can only have as
     * many non-deleted templates as allotted in your current &lt;a
     * href="https://dashboard.lob.com/#/settings/editions" target="_blank"&gt;Print &amp; Mail
     * Edition&lt;/a&gt;. If you attempt to create a template past your limit, you will receive a `403`
     * error. There is no limit in Test mode.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestCreateTemplate() throws Exception {
        // Parameters for the API call
        String html = 
                "<html>HTML for {{name}}</html>";
        String description = null;
        Map<String, String> metadata = ApiHelper.deserialize(
                "{\r\n  \"spiffy\": \"true\"\r\n}",
                new TypeReference<Map<String, String>>(){});
        EngineEnum engine = null;
        List<String> requiredVars = null;

        // Set callback and perform API call
        Template result = null;
        try {
            result = controller.createTemplate(html, description, metadata, engine, requiredVars);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("ratelimit-limit", TestHelper.NULL_STRING);
        headers.put("ratelimit-remaining", TestHelper.NULL_STRING);
        headers.put("ratelimit-reset", TestHelper.NULL_STRING);
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertTrue("Response body does not match in keys", 
                TestHelper.isJsonObjectProperSubsetOf(
                "{\"id\":\"tmpl_c94e83ca2cd5121\",\"description\":\"Test Template\",\"versions\":[{"
                + "\"id\":\"vrsn_362184d96d9b0c9\",\"suggest_json_editor\":true,\"description\":\"T"
                + "est Template\",\"engine\":\"legacy\",\"html\":\"<html>HTML for {{name}}</html>"
                + "\",\"date_created\":\"2017-11-07T22:56:10.962Z\",\"date_modified\":\"2017-11-07T"
                + "22:56:10.962Z\",\"object\":\"version\"}],\"published_version\":{\"id\":\"vrsn_36"
                + "2184d96d9b0c9\",\"suggest_json_editor\":false,\"description\":\"Test Template\","
                + "\"engine\":\"handlebars\",\"html\":\"<html>HTML for {{name}}</html>\",\"date_cre"
                + "ated\":\"2017-11-07T22:56:10.962Z\",\"date_modified\":\"2017-11-07T22:56:10.962Z"
                + "\",\"object\":\"version\"},\"metadata\":{},\"date_created\":\"2017-11-07T22:56:1"
                + "0.962Z\",\"date_modified\":\"2017-11-07T22:56:10.962Z\",\"object\":\"template\"}"
                + "",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()), 
                false, true, false));
    }

}
