/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * CodeEnum to be used.
 */
public enum CodeEnum {
    BAD_REQUEST,

    CONFLICT,

    FEATURE_LIMIT_REACHED,

    INTERNAL_SERVER_ERROR,

    INVALID,

    NOT_DELETABLE,

    NOT_FOUND,

    REQUEST_TIMEOUT,

    SERVICE_UNAVAILABLE,

    UNRECOGNIZED_ENDPOINT,

    UNSUPPORTED_LOB_VERSION,

    ADDRESS_LENGTH_EXCEEDS_LIMIT,

    BANK_ACCOUNT_ALREADY_VERIFIED,

    BANK_ERROR,

    BILLING_ADDRESS_REQUIRED,

    CUSTOM_ENVELOPE_INVENTORY_DEPLETED,

    DELETED_BANK_ACCOUNT,

    FAILED_DELIVERABILITY_STRICTNESS,

    FILE_PAGES_BELOW_MIN,

    FILE_PAGES_EXCEED_MAX,

    FILE_SIZE_EXCEEDS_LIMIT,

    FOREIGN_RETURN_ADDRESS,

    INCONSISTENT_PAGE_DIMENSIONS,

    INVALID_BANK_ACCOUNT,

    INVALID_BANK_ACCOUNT_VERIFICATION,

    INVALID_CHECK_INTERNATIONAL,

    INVALID_COUNTRY_COVID,

    INVALID_FILE,

    INVALID_FILE_DIMENSIONS,

    INVALID_FILE_DOWNLOAD_TIME,

    INVALID_FILE_URL,

    INVALID_IMAGE_DPI,

    INVALID_INTERNATIONAL_FEATURE,

    INVALID_PERFORATION_RETURN_ENVELOPE,

    INVALID_TEMPLATE_HTML,

    MAIL_USE_TYPE_CAN_NOT_BE_NULL,

    MERGE_VARIABLE_REQUIRED,

    MERGE_VARIABLE_WHITESPACE,

    PAYMENT_METHOD_UNVERIFIED,

    PDF_ENCRYPTED,

    SPECIAL_CHARACTERS_RESTRICTED,

    UNEMBEDDED_FONTS,

    EMAIL_REQUIRED,

    INVALID_API_KEY,

    PUBLISHABLE_KEY_NOT_ALLOWED,

    RATE_LIMIT_EXCEEDED,

    UNAUTHORIZED,

    UNAUTHORIZED_TOKEN;


    private static TreeMap<String, CodeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        BAD_REQUEST.value = "bad_request";
        CONFLICT.value = "conflict";
        FEATURE_LIMIT_REACHED.value = "feature_limit_reached";
        INTERNAL_SERVER_ERROR.value = "internal_server_error";
        INVALID.value = "invalid";
        NOT_DELETABLE.value = "not_deletable";
        NOT_FOUND.value = "not_found";
        REQUEST_TIMEOUT.value = "request_timeout";
        SERVICE_UNAVAILABLE.value = "service_unavailable";
        UNRECOGNIZED_ENDPOINT.value = "unrecognized_endpoint";
        UNSUPPORTED_LOB_VERSION.value = "unsupported_lob_version";
        ADDRESS_LENGTH_EXCEEDS_LIMIT.value = "address_length_exceeds_limit";
        BANK_ACCOUNT_ALREADY_VERIFIED.value = "bank_account_already_verified";
        BANK_ERROR.value = "bank_error";
        BILLING_ADDRESS_REQUIRED.value = "billing_address_required";
        CUSTOM_ENVELOPE_INVENTORY_DEPLETED.value = "custom_envelope_inventory_depleted";
        DELETED_BANK_ACCOUNT.value = "deleted_bank_account";
        FAILED_DELIVERABILITY_STRICTNESS.value = "failed_deliverability_strictness";
        FILE_PAGES_BELOW_MIN.value = "file_pages_below_min";
        FILE_PAGES_EXCEED_MAX.value = "file_pages_exceed_max";
        FILE_SIZE_EXCEEDS_LIMIT.value = "file_size_exceeds_limit";
        FOREIGN_RETURN_ADDRESS.value = "foreign_return_address";
        INCONSISTENT_PAGE_DIMENSIONS.value = "inconsistent_page_dimensions";
        INVALID_BANK_ACCOUNT.value = "invalid_bank_account";
        INVALID_BANK_ACCOUNT_VERIFICATION.value = "invalid_bank_account_verification";
        INVALID_CHECK_INTERNATIONAL.value = "invalid_check_international";
        INVALID_COUNTRY_COVID.value = "invalid_country_covid";
        INVALID_FILE.value = "invalid_file";
        INVALID_FILE_DIMENSIONS.value = "invalid_file_dimensions";
        INVALID_FILE_DOWNLOAD_TIME.value = "invalid_file_download_time";
        INVALID_FILE_URL.value = "invalid_file_url";
        INVALID_IMAGE_DPI.value = "invalid_image_dpi";
        INVALID_INTERNATIONAL_FEATURE.value = "invalid_international_feature";
        INVALID_PERFORATION_RETURN_ENVELOPE.value = "invalid_perforation_return_envelope";
        INVALID_TEMPLATE_HTML.value = "invalid_template_html";
        MAIL_USE_TYPE_CAN_NOT_BE_NULL.value = "mail_use_type_can_not_be_null";
        MERGE_VARIABLE_REQUIRED.value = "merge_variable_required";
        MERGE_VARIABLE_WHITESPACE.value = "merge_variable_whitespace";
        PAYMENT_METHOD_UNVERIFIED.value = "payment_method_unverified";
        PDF_ENCRYPTED.value = "pdf_encrypted";
        SPECIAL_CHARACTERS_RESTRICTED.value = "special_characters_restricted";
        UNEMBEDDED_FONTS.value = "unembedded_fonts";
        EMAIL_REQUIRED.value = "email_required";
        INVALID_API_KEY.value = "invalid_api_key";
        PUBLISHABLE_KEY_NOT_ALLOWED.value = "publishable_key_not_allowed";
        RATE_LIMIT_EXCEEDED.value = "rate_limit_exceeded";
        UNAUTHORIZED.value = "unauthorized";
        UNAUTHORIZED_TOKEN.value = "unauthorized_token";

        valueMap.put("bad_request", BAD_REQUEST);
        valueMap.put("conflict", CONFLICT);
        valueMap.put("feature_limit_reached", FEATURE_LIMIT_REACHED);
        valueMap.put("internal_server_error", INTERNAL_SERVER_ERROR);
        valueMap.put("invalid", INVALID);
        valueMap.put("not_deletable", NOT_DELETABLE);
        valueMap.put("not_found", NOT_FOUND);
        valueMap.put("request_timeout", REQUEST_TIMEOUT);
        valueMap.put("service_unavailable", SERVICE_UNAVAILABLE);
        valueMap.put("unrecognized_endpoint", UNRECOGNIZED_ENDPOINT);
        valueMap.put("unsupported_lob_version", UNSUPPORTED_LOB_VERSION);
        valueMap.put("address_length_exceeds_limit", ADDRESS_LENGTH_EXCEEDS_LIMIT);
        valueMap.put("bank_account_already_verified", BANK_ACCOUNT_ALREADY_VERIFIED);
        valueMap.put("bank_error", BANK_ERROR);
        valueMap.put("billing_address_required", BILLING_ADDRESS_REQUIRED);
        valueMap.put("custom_envelope_inventory_depleted", CUSTOM_ENVELOPE_INVENTORY_DEPLETED);
        valueMap.put("deleted_bank_account", DELETED_BANK_ACCOUNT);
        valueMap.put("failed_deliverability_strictness", FAILED_DELIVERABILITY_STRICTNESS);
        valueMap.put("file_pages_below_min", FILE_PAGES_BELOW_MIN);
        valueMap.put("file_pages_exceed_max", FILE_PAGES_EXCEED_MAX);
        valueMap.put("file_size_exceeds_limit", FILE_SIZE_EXCEEDS_LIMIT);
        valueMap.put("foreign_return_address", FOREIGN_RETURN_ADDRESS);
        valueMap.put("inconsistent_page_dimensions", INCONSISTENT_PAGE_DIMENSIONS);
        valueMap.put("invalid_bank_account", INVALID_BANK_ACCOUNT);
        valueMap.put("invalid_bank_account_verification", INVALID_BANK_ACCOUNT_VERIFICATION);
        valueMap.put("invalid_check_international", INVALID_CHECK_INTERNATIONAL);
        valueMap.put("invalid_country_covid", INVALID_COUNTRY_COVID);
        valueMap.put("invalid_file", INVALID_FILE);
        valueMap.put("invalid_file_dimensions", INVALID_FILE_DIMENSIONS);
        valueMap.put("invalid_file_download_time", INVALID_FILE_DOWNLOAD_TIME);
        valueMap.put("invalid_file_url", INVALID_FILE_URL);
        valueMap.put("invalid_image_dpi", INVALID_IMAGE_DPI);
        valueMap.put("invalid_international_feature", INVALID_INTERNATIONAL_FEATURE);
        valueMap.put("invalid_perforation_return_envelope", INVALID_PERFORATION_RETURN_ENVELOPE);
        valueMap.put("invalid_template_html", INVALID_TEMPLATE_HTML);
        valueMap.put("mail_use_type_can_not_be_null", MAIL_USE_TYPE_CAN_NOT_BE_NULL);
        valueMap.put("merge_variable_required", MERGE_VARIABLE_REQUIRED);
        valueMap.put("merge_variable_whitespace", MERGE_VARIABLE_WHITESPACE);
        valueMap.put("payment_method_unverified", PAYMENT_METHOD_UNVERIFIED);
        valueMap.put("pdf_encrypted", PDF_ENCRYPTED);
        valueMap.put("special_characters_restricted", SPECIAL_CHARACTERS_RESTRICTED);
        valueMap.put("unembedded_fonts", UNEMBEDDED_FONTS);
        valueMap.put("email_required", EMAIL_REQUIRED);
        valueMap.put("invalid_api_key", INVALID_API_KEY);
        valueMap.put("publishable_key_not_allowed", PUBLISHABLE_KEY_NOT_ALLOWED);
        valueMap.put("rate_limit_exceeded", RATE_LIMIT_EXCEEDED);
        valueMap.put("unauthorized", UNAUTHORIZED);
        valueMap.put("unauthorized_token", UNAUTHORIZED_TOKEN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static CodeEnum constructFromString(String toConvert) throws IOException {
        CodeEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static CodeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CodeEnum values to list of string values.
     * @param toConvert The list of CodeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<CodeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (CodeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 