/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Status4Enum to be used.
 */
public enum Status4Enum {
    VALIDATED,

    FAILED,

    PROCESSING;


    private static TreeMap<String, Status4Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        VALIDATED.value = "Validated";
        FAILED.value = "Failed";
        PROCESSING.value = "Processing";

        valueMap.put("Validated", VALIDATED);
        valueMap.put("Failed", FAILED);
        valueMap.put("Processing", PROCESSING);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Status4Enum constructFromString(String toConvert) throws IOException {
        Status4Enum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Status4Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Status4Enum values to list of string values.
     * @param toConvert The list of Status4Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Status4Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Status4Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 