/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.18
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BuckslipOrder
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-28T10:58:18.138843-08:00[America/Los_Angeles]")
public class BuckslipOrder {
  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  private OffsetDateTime dateCreated;

  public static final String SERIALIZED_NAME_DATE_MODIFIED = "date_modified";
  @SerializedName(SERIALIZED_NAME_DATE_MODIFIED)
  private OffsetDateTime dateModified;

  public static final String SERIALIZED_NAME_DELETED = "deleted";
  @SerializedName(SERIALIZED_NAME_DELETED)
  private Boolean deleted;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private String _object;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_BUCKSLIP_ID = "buckslip_id";
  @SerializedName(SERIALIZED_NAME_BUCKSLIP_ID)
  private String buckslipId;

  /**
   * The status of the buckslip order.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("pending"),
    
    PRINTING("printing"),
    
    AVAILABLE("available"),
    
    CANCELLED("cancelled"),
    
    DEPLETED("depleted");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_QUANTITY_ORDERED = "quantity_ordered";
  @SerializedName(SERIALIZED_NAME_QUANTITY_ORDERED)
  private BigDecimal quantityOrdered = new BigDecimal("0");

  public static final String SERIALIZED_NAME_UNIT_PRICE = "unit_price";
  @SerializedName(SERIALIZED_NAME_UNIT_PRICE)
  private BigDecimal unitPrice = new BigDecimal("0");

  public static final String SERIALIZED_NAME_INVENTORY = "inventory";
  @SerializedName(SERIALIZED_NAME_INVENTORY)
  private BigDecimal inventory = new BigDecimal("0");

  public static final String SERIALIZED_NAME_CANCELLED_REASON = "cancelled_reason";
  @SerializedName(SERIALIZED_NAME_CANCELLED_REASON)
  private String cancelledReason;

  public static final String SERIALIZED_NAME_AVAILABILITY_DATE = "availability_date";
  @SerializedName(SERIALIZED_NAME_AVAILABILITY_DATE)
  private OffsetDateTime availabilityDate;

  public static final String SERIALIZED_NAME_EXPECTED_AVAILABILITY_DATE = "expected_availability_date";
  @SerializedName(SERIALIZED_NAME_EXPECTED_AVAILABILITY_DATE)
  private OffsetDateTime expectedAvailabilityDate;

  public BuckslipOrder() {
  }

  public BuckslipOrder dateCreated(OffsetDateTime dateCreated) {
    
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * A timestamp in ISO 8601 format of the date the resource was created.
   * @return dateCreated
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }


  public void setDateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  public BuckslipOrder dateModified(OffsetDateTime dateModified) {
    
    this.dateModified = dateModified;
    return this;
  }

   /**
   * A timestamp in ISO 8601 format of the date the resource was last modified.
   * @return dateModified
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getDateModified() {
    return dateModified;
  }


  public void setDateModified(OffsetDateTime dateModified) {
    this.dateModified = dateModified;
  }


  public BuckslipOrder deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Only returned if the resource has been successfully deleted.
   * @return deleted
  **/
  @javax.annotation.Nullable
  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public BuckslipOrder _object(String _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * Value is resource type.
   * @return _object
  **/
  @javax.annotation.Nonnull
  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    this._object = _object;
  }


  public BuckslipOrder id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Unique identifier prefixed with &#x60;bo_&#x60;.
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BuckslipOrder buckslipId(String buckslipId) {
    
    this.buckslipId = buckslipId;
    return this;
  }

   /**
   * Unique identifier prefixed with &#x60;bck_&#x60;.
   * @return buckslipId
  **/
  @javax.annotation.Nullable
  public String getBuckslipId() {
    return buckslipId;
  }


  public void setBuckslipId(String buckslipId) {
    this.buckslipId = buckslipId;
  }


  public BuckslipOrder status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status of the buckslip order.
   * @return status
  **/
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public BuckslipOrder quantityOrdered(BigDecimal quantityOrdered) {
    
    this.quantityOrdered = quantityOrdered;
    return this;
  }

   /**
   * The quantity of buckslips ordered.
   * @return quantityOrdered
  **/
  @javax.annotation.Nullable
  public BigDecimal getQuantityOrdered() {
    return quantityOrdered;
  }


  public void setQuantityOrdered(BigDecimal quantityOrdered) {
    this.quantityOrdered = quantityOrdered;
  }


  public BuckslipOrder unitPrice(BigDecimal unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * The unit price for the buckslip order.
   * @return unitPrice
  **/
  @javax.annotation.Nullable
  public BigDecimal getUnitPrice() {
    return unitPrice;
  }


  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }


  public BuckslipOrder inventory(BigDecimal inventory) {
    
    this.inventory = inventory;
    return this;
  }

   /**
   * The inventory of the buckslip order.
   * @return inventory
  **/
  @javax.annotation.Nullable
  public BigDecimal getInventory() {
    return inventory;
  }


  public void setInventory(BigDecimal inventory) {
    this.inventory = inventory;
  }


  public BuckslipOrder cancelledReason(String cancelledReason) {
    
    this.cancelledReason = cancelledReason;
    return this;
  }

   /**
   * The reason for cancellation.
   * @return cancelledReason
  **/
  @javax.annotation.Nullable
  public String getCancelledReason() {
    return cancelledReason;
  }


  public void setCancelledReason(String cancelledReason) {
    this.cancelledReason = cancelledReason;
  }


  public BuckslipOrder availabilityDate(OffsetDateTime availabilityDate) {
    
    this.availabilityDate = availabilityDate;
    return this;
  }

   /**
   * A timestamp in ISO 8601 format of the date the resource was created.
   * @return availabilityDate
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getAvailabilityDate() {
    return availabilityDate;
  }


  public void setAvailabilityDate(OffsetDateTime availabilityDate) {
    this.availabilityDate = availabilityDate;
  }


  public BuckslipOrder expectedAvailabilityDate(OffsetDateTime expectedAvailabilityDate) {
    
    this.expectedAvailabilityDate = expectedAvailabilityDate;
    return this;
  }

   /**
   * The fixed deadline for the buckslips to be printed.
   * @return expectedAvailabilityDate
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getExpectedAvailabilityDate() {
    return expectedAvailabilityDate;
  }


  public void setExpectedAvailabilityDate(OffsetDateTime expectedAvailabilityDate) {
    this.expectedAvailabilityDate = expectedAvailabilityDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuckslipOrder buckslipOrder = (BuckslipOrder) o;
    return Objects.equals(this.dateCreated, buckslipOrder.dateCreated) &&
        Objects.equals(this.dateModified, buckslipOrder.dateModified) &&
        Objects.equals(this.deleted, buckslipOrder.deleted) &&
        Objects.equals(this._object, buckslipOrder._object) &&
        Objects.equals(this.id, buckslipOrder.id) &&
        Objects.equals(this.buckslipId, buckslipOrder.buckslipId) &&
        Objects.equals(this.status, buckslipOrder.status) &&
        Objects.equals(this.quantityOrdered, buckslipOrder.quantityOrdered) &&
        Objects.equals(this.unitPrice, buckslipOrder.unitPrice) &&
        Objects.equals(this.inventory, buckslipOrder.inventory) &&
        Objects.equals(this.cancelledReason, buckslipOrder.cancelledReason) &&
        Objects.equals(this.availabilityDate, buckslipOrder.availabilityDate) &&
        Objects.equals(this.expectedAvailabilityDate, buckslipOrder.expectedAvailabilityDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateCreated, dateModified, deleted, _object, id, buckslipId, status, quantityOrdered, unitPrice, inventory, cancelledReason, availabilityDate, expectedAvailabilityDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuckslipOrder {\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    buckslipId: ").append(toIndentedString(buckslipId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    quantityOrdered: ").append(toIndentedString(quantityOrdered)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("    cancelledReason: ").append(toIndentedString(cancelledReason)).append("\n");
    sb.append("    availabilityDate: ").append(toIndentedString(availabilityDate)).append("\n");
    sb.append("    expectedAvailabilityDate: ").append(toIndentedString(expectedAvailabilityDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date_created");
    openapiFields.add("date_modified");
    openapiFields.add("deleted");
    openapiFields.add("object");
    openapiFields.add("id");
    openapiFields.add("buckslip_id");
    openapiFields.add("status");
    openapiFields.add("quantity_ordered");
    openapiFields.add("unit_price");
    openapiFields.add("inventory");
    openapiFields.add("cancelled_reason");
    openapiFields.add("availability_date");
    openapiFields.add("expected_availability_date");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("date_created");
    openapiRequiredFields.add("date_modified");
    openapiRequiredFields.add("object");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BuckslipOrder
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BuckslipOrder.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BuckslipOrder is not found in the empty JSON string", BuckslipOrder.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BuckslipOrder.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BuckslipOrder` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BuckslipOrder.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("buckslip_id") != null && !jsonObj.get("buckslip_id").isJsonNull()) && !jsonObj.get("buckslip_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buckslip_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buckslip_id").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("cancelled_reason") != null && !jsonObj.get("cancelled_reason").isJsonNull()) && !jsonObj.get("cancelled_reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cancelled_reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancelled_reason").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BuckslipOrder.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BuckslipOrder' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BuckslipOrder> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BuckslipOrder.class));

       return (TypeAdapter<T>) new TypeAdapter<BuckslipOrder>() {
           @Override
           public void write(JsonWriter out, BuckslipOrder value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BuckslipOrder read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BuckslipOrder given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BuckslipOrder
  * @throws IOException if the JSON string is invalid with respect to BuckslipOrder
  */
  public static BuckslipOrder fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BuckslipOrder.class);
  }

 /**
  * Convert an instance of BuckslipOrder to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

