/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.18
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Engine;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TemplateVersionUpdatable
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-28T10:58:18.138843-08:00[America/Los_Angeles]")
public class TemplateVersionUpdatable {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ENGINE = "engine";
  @SerializedName(SERIALIZED_NAME_ENGINE)
  private Engine engine = Engine.LEGACY;

  public static final String SERIALIZED_NAME_REQUIRED_VARS = "required_vars";
  @SerializedName(SERIALIZED_NAME_REQUIRED_VARS)
  private List<String> requiredVars;

  public TemplateVersionUpdatable() {
  }

  public TemplateVersionUpdatable description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * An internal description that identifies this resource. Must be no longer than 255 characters. 
   * @return description
  **/
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public TemplateVersionUpdatable engine(Engine engine) {
    
    this.engine = engine;
    return this;
  }

   /**
   * Get engine
   * @return engine
  **/
  @javax.annotation.Nullable
  public Engine getEngine() {
    return engine;
  }


  public void setEngine(Engine engine) {
    this.engine = engine;
  }


  public TemplateVersionUpdatable requiredVars(List<String> requiredVars) {
    
    this.requiredVars = requiredVars;
    return this;
  }

  public TemplateVersionUpdatable addRequiredVarsItem(String requiredVarsItem) {
    if (this.requiredVars == null) {
      this.requiredVars = new ArrayList<>();
    }
    this.requiredVars.add(requiredVarsItem);
    return this;
  }

   /**
   * An array of required variables to be used in a template. Only available for &#x60;handlebars&#x60; templates. 
   * @return requiredVars
  **/
  @javax.annotation.Nullable
  public List<String> getRequiredVars() {
    return requiredVars;
  }


  public void setRequiredVars(List<String> requiredVars) {
    this.requiredVars = requiredVars;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateVersionUpdatable templateVersionUpdatable = (TemplateVersionUpdatable) o;
    return Objects.equals(this.description, templateVersionUpdatable.description) &&
        Objects.equals(this.engine, templateVersionUpdatable.engine) &&
        Objects.equals(this.requiredVars, templateVersionUpdatable.requiredVars);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, engine, requiredVars);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateVersionUpdatable {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    engine: ").append(toIndentedString(engine)).append("\n");
    sb.append("    requiredVars: ").append(toIndentedString(requiredVars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("engine");
    openapiFields.add("required_vars");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TemplateVersionUpdatable
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TemplateVersionUpdatable.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateVersionUpdatable is not found in the empty JSON string", TemplateVersionUpdatable.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TemplateVersionUpdatable.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TemplateVersionUpdatable` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // validate the optional field `engine`
      if (jsonObj.get("engine") != null && !jsonObj.get("engine").isJsonNull()) {
        Engine.validateJsonElement(jsonObj.get("engine"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("required_vars") != null && !jsonObj.get("required_vars").isJsonNull() && !jsonObj.get("required_vars").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `required_vars` to be an array in the JSON string but got `%s`", jsonObj.get("required_vars").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateVersionUpdatable.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateVersionUpdatable' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateVersionUpdatable> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateVersionUpdatable.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateVersionUpdatable>() {
           @Override
           public void write(JsonWriter out, TemplateVersionUpdatable value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateVersionUpdatable read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateVersionUpdatable given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateVersionUpdatable
  * @throws IOException if the JSON string is invalid with respect to TemplateVersionUpdatable
  */
  public static TemplateVersionUpdatable fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateVersionUpdatable.class);
  }

 /**
  * Convert an instance of TemplateVersionUpdatable to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

