/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.18
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CompanyValidation;
import org.openapitools.client.model.RecipientValidation;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IdentityValidation
 */
public class IdentityValidationTest {
    private final IdentityValidation model = new IdentityValidation();

    /**
     * Model tests for IdentityValidation
     */
    @Test
    public void testIdentityValidation() {
        // TODO: test IdentityValidation
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'recipient'
     */
    @Test
    public void recipientTest() {
        // TODO: test recipient
    }

    /**
     * Test the property 'primaryLine'
     */
    @Test
    public void primaryLineTest() {
        // TODO: test primaryLine
    }

    /**
     * Test the property 'secondaryLine'
     */
    @Test
    public void secondaryLineTest() {
        // TODO: test secondaryLine
    }

    /**
     * Test the property 'urbanization'
     */
    @Test
    public void urbanizationTest() {
        // TODO: test urbanization
    }

    /**
     * Test the property 'lastLine'
     */
    @Test
    public void lastLineTest() {
        // TODO: test lastLine
    }

    /**
     * Test the property 'score'
     */
    @Test
    public void scoreTest() {
        // TODO: test score
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    public void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

}
