/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.18
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AddressPlacement;
import org.openapitools.client.model.ExtraService;
import org.openapitools.client.model.LetterAddOnTypes;
import org.openapitools.client.model.MailType;
import org.openapitools.client.model.QrCodeCampaigns;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LetterDetailsWritable
 */
public class LetterDetailsWritableTest {
    private final LetterDetailsWritable model = new LetterDetailsWritable();

    /**
     * Model tests for LetterDetailsWritable
     */
    @Test
    public void testLetterDetailsWritable() {
        // TODO: test LetterDetailsWritable
    }

    /**
     * Test the property 'addressPlacement'
     */
    @Test
    public void addressPlacementTest() {
        // TODO: test addressPlacement
    }

    /**
     * Test the property 'addOnTypes'
     */
    @Test
    public void addOnTypesTest() {
        // TODO: test addOnTypes
    }

    /**
     * Test the property 'buckslips'
     */
    @Test
    public void buckslipsTest() {
        // TODO: test buckslips
    }

    /**
     * Test the property 'cards'
     */
    @Test
    public void cardsTest() {
        // TODO: test cards
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'customEnvelope'
     */
    @Test
    public void customEnvelopeTest() {
        // TODO: test customEnvelope
    }

    /**
     * Test the property 'doubleSided'
     */
    @Test
    public void doubleSidedTest() {
        // TODO: test doubleSided
    }

    /**
     * Test the property 'extraService'
     */
    @Test
    public void extraServiceTest() {
        // TODO: test extraService
    }

    /**
     * Test the property 'mailType'
     */
    @Test
    public void mailTypeTest() {
        // TODO: test mailType
    }

    /**
     * Test the property 'qrCode'
     */
    @Test
    public void qrCodeTest() {
        // TODO: test qrCode
    }

}
