/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.18
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.AddressPlacement;
import org.openapitools.client.model.ExtraService;
import org.openapitools.client.model.InputFromFrom;
import org.openapitools.client.model.InputToTo;
import org.openapitools.client.model.LtrFile;
import org.openapitools.client.model.LtrUseType;
import org.openapitools.client.model.MailType;
import org.openapitools.client.model.QrCode;
import org.openapitools.client.model.ReturnEnvelopeUserProvided;
import org.openapitools.client.model.SendDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LetterEditable
 */
public class LetterEditableTest {
    private final LetterEditable model = new LetterEditable();

    /**
     * Model tests for LetterEditable
     */
    @Test
    public void testLetterEditable() {
        // TODO: test LetterEditable
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'mailType'
     */
    @Test
    public void mailTypeTest() {
        // TODO: test mailType
    }

    /**
     * Test the property 'mergeVariables'
     */
    @Test
    public void mergeVariablesTest() {
        // TODO: test mergeVariables
    }

    /**
     * Test the property 'sendDate'
     */
    @Test
    public void sendDateTest() {
        // TODO: test sendDate
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'extraService'
     */
    @Test
    public void extraServiceTest() {
        // TODO: test extraService
    }

    /**
     * Test the property 'cards'
     */
    @Test
    public void cardsTest() {
        // TODO: test cards
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'doubleSided'
     */
    @Test
    public void doubleSidedTest() {
        // TODO: test doubleSided
    }

    /**
     * Test the property 'addressPlacement'
     */
    @Test
    public void addressPlacementTest() {
        // TODO: test addressPlacement
    }

    /**
     * Test the property 'returnEnvelope'
     */
    @Test
    public void returnEnvelopeTest() {
        // TODO: test returnEnvelope
    }

    /**
     * Test the property 'perforatedPage'
     */
    @Test
    public void perforatedPageTest() {
        // TODO: test perforatedPage
    }

    /**
     * Test the property 'customEnvelope'
     */
    @Test
    public void customEnvelopeTest() {
        // TODO: test customEnvelope
    }

    /**
     * Test the property 'billingGroupId'
     */
    @Test
    public void billingGroupIdTest() {
        // TODO: test billingGroupId
    }

    /**
     * Test the property 'qrCode'
     */
    @Test
    public void qrCodeTest() {
        // TODO: test qrCode
    }

    /**
     * Test the property 'useType'
     */
    @Test
    public void useTypeTest() {
        // TODO: test useType
    }

    /**
     * Test the property 'fsc'
     */
    @Test
    public void fscTest() {
        // TODO: test fsc
    }

}
