/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.18
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.AddressUs;
import org.openapitools.client.model.MailType;
import org.openapitools.client.model.PostcardSize;
import org.openapitools.client.model.PscUseType;
import org.openapitools.client.model.SendDate;
import org.openapitools.client.model.Thumbnail;
import org.openapitools.client.model.TrackingEventNormal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Postcard
 */
public class PostcardTest {
    private final Postcard model = new Postcard();

    /**
     * Model tests for Postcard
     */
    @Test
    public void testPostcard() {
        // TODO: test Postcard
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'mailType'
     */
    @Test
    public void mailTypeTest() {
        // TODO: test mailType
    }

    /**
     * Test the property 'mergeVariables'
     */
    @Test
    public void mergeVariablesTest() {
        // TODO: test mergeVariables
    }

    /**
     * Test the property 'sendDate'
     */
    @Test
    public void sendDateTest() {
        // TODO: test sendDate
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'thumbnails'
     */
    @Test
    public void thumbnailsTest() {
        // TODO: test thumbnails
    }

    /**
     * Test the property 'expectedDeliveryDate'
     */
    @Test
    public void expectedDeliveryDateTest() {
        // TODO: test expectedDeliveryDate
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateModified'
     */
    @Test
    public void dateModifiedTest() {
        // TODO: test dateModified
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'frontTemplateId'
     */
    @Test
    public void frontTemplateIdTest() {
        // TODO: test frontTemplateId
    }

    /**
     * Test the property 'backTemplateId'
     */
    @Test
    public void backTemplateIdTest() {
        // TODO: test backTemplateId
    }

    /**
     * Test the property 'frontTemplateVersionId'
     */
    @Test
    public void frontTemplateVersionIdTest() {
        // TODO: test frontTemplateVersionId
    }

    /**
     * Test the property 'backTemplateVersionId'
     */
    @Test
    public void backTemplateVersionIdTest() {
        // TODO: test backTemplateVersionId
    }

    /**
     * Test the property 'trackingEvents'
     */
    @Test
    public void trackingEventsTest() {
        // TODO: test trackingEvents
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'campaignId'
     */
    @Test
    public void campaignIdTest() {
        // TODO: test campaignId
    }

    /**
     * Test the property 'useType'
     */
    @Test
    public void useTypeTest() {
        // TODO: test useType
    }

    /**
     * Test the property 'fsc'
     */
    @Test
    public void fscTest() {
        // TODO: test fsc
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'failureReason'
     */
    @Test
    public void failureReasonTest() {
        // TODO: test failureReason
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

}
