/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CarrierRouteType - The type of `components[carrier_route]`. For more detailed information about
 * each carrier route type, see [US Verification Details](#tag/US-Verification-Types).
 * 
 */
public enum CarrierRouteType {
    CITY_DELIVERY("city_delivery"),
    RURAL_ROUTE("rural_route"),
    HIGHWAY_CONTRACT("highway_contract"),
    PO_BOX("po_box"),
    GENERAL_DELIVERY("general_delivery");

    @JsonValue
    public final String value;

    private CarrierRouteType(String value) {
        this.value = value;
    }
}
