/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DpvVacant - Indicates that an address was once deliverable, but has become vacant and is no longer receiving deliveries. Possible values are:
 * * `Y` –– Address is vacant.
 * * `N` –– Address is not vacant.
 * * `''` –– A DPV match is not made (`deliverability_analysis[dpv_confirmation]` is `N` or an empty string).
 * 
 */
public enum DpvVacant {
    Y("Y"),
    N("N"),
    UNKNOWN("");

    @JsonValue
    public final String value;

    private DpvVacant(String value) {
        this.value = value;
    }
}
