/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class LinksResponse {
    /**
     * The number of results in the current response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("count")
    public Long count;

    public LinksResponse withCount(Long count) {
        this.count = count;
        return this;
    }
    
    /**
     * How many results to return.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("limit")
    public Long limit;

    public LinksResponse withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * An integer that designates the offset at which to begin returning results. Defaults to 0.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offset")
    public Long offset;

    public LinksResponse withOffset(Long offset) {
        this.offset = offset;
        return this;
    }
    
    /**
     * list of links
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public LinkResponse[] data;

    public LinksResponse withData(LinkResponse[] data) {
        this.data = data;
        return this;
    }
    
    public LinksResponse(){}
}
