/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RequiredAddressColumnMapping - The mapping of column headers in your file to Lob-required fields for the resource created. See our &lt;a href="https://help.lob.com/print-and-mail/building-a-mail-strategy/campaign-or-triggered-sends/campaign-audience-guide#required-columns-2" target="_blank"&gt;Campaign Audience Guide&lt;/a&gt; for additional details.
 */

public class RequiredAddressColumnMapping {
    /**
     * The column header from the csv file that should be mapped to the required field `name`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public RequiredAddressColumnMapping withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The column header from the csv file that should be mapped to the required field `address_line1`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address_line1")
    public String addressLine1;

    public RequiredAddressColumnMapping withAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
        return this;
    }
    
    /**
     * The column header from the csv file that should be mapped to the required field `address_city`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address_city")
    public String addressCity;

    public RequiredAddressColumnMapping withAddressCity(String addressCity) {
        this.addressCity = addressCity;
        return this;
    }
    
    /**
     * The column header from the csv file that should be mapped to the required field `address_state`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address_state")
    public String addressState;

    public RequiredAddressColumnMapping withAddressState(String addressState) {
        this.addressState = addressState;
        return this;
    }
    
    /**
     * The column header from the csv file that should be mapped to the required field `address_zip`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address_zip")
    public String addressZip;

    public RequiredAddressColumnMapping withAddressZip(String addressZip) {
        this.addressZip = addressZip;
        return this;
    }
    
    public RequiredAddressColumnMapping(){}
}
