/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi;

import org.openapis.openapi.utils.HTTPClient;
import org.openapis.openapi.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0.0";
	public String sdkVersion = "0.0.1";
	public String genVersion = "2.202.2";
	public String userAgent = "speakeasy-sdk/java 0.0.1 2.202.2 1.0.0 <no value>";
	
	
}