/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.18
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.QrCodesList200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QrCodesApi
 */
@Disabled
public class QrCodesApiTest {

    private final QrCodesApi api = new QrCodesApi();

    /**
     * List
     *
     * Returns a list of your QR codes. The QR codes are returned sorted by scan date, with the most recently scanned QR codes appearing first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void qrCodesListTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        List<String> include = null;
        Map<String, String> dateCreated = null;
        Boolean scanned = null;
        List<String> resourceIds = null;
        QrCodesList200Response response = api.qrCodesList(limit, offset, include, dateCreated, scanned, resourceIds);
        // TODO: test validations
    }

}
