/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class BankAccountVerifyResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public BankAccountVerifyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public BankAccountVerifyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public BankAccountVerifyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Returns a bank_account object
     */
    
    public org.openapis.openapi.models.shared.BankAccount bankAccount;

    public BankAccountVerifyResponse withBankAccount(org.openapis.openapi.models.shared.BankAccount bankAccount) {
        this.bankAccount = bankAccount;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public BankAccountVerifyResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    public BankAccountVerifyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse, @JsonProperty("Headers") java.util.Map<String, String[]> headers) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.headers = headers;
  }
}
