/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;


public class CheckCancelRequest {
    /**
     * id of the check
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=chk_id")
    public String chkId;

    public CheckCancelRequest withChkId(String chkId) {
        this.chkId = chkId;
        return this;
    }
    
    public CheckCancelRequest(@JsonProperty("chk_id") String chkId) {
        this.chkId = chkId;
  }
}
