/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;
import org.openapis.openapi.utils.DateTimeDeserializer;
import org.openapis.openapi.utils.DateTimeSerializer;

/**
 * ExportRetrieveResponseBody - Returns an export object
 */

public class ExportRetrieveResponseBody {
    /**
     * Unique identifier prefixed with `ex_`.
     */
    @JsonProperty("id")
    public String id;

    public ExportRetrieveResponseBody withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * A timestamp in ISO 8601 format of the date the export was created
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("dateCreated")
    public OffsetDateTime dateCreated;

    public ExportRetrieveResponseBody withDateCreated(OffsetDateTime dateCreated) {
        this.dateCreated = dateCreated;
        return this;
    }
    
    /**
     * A timestamp in ISO 8601 format of the date the export was last modified
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("dateModified")
    public OffsetDateTime dateModified;

    public ExportRetrieveResponseBody withDateModified(OffsetDateTime dateModified) {
        this.dateModified = dateModified;
        return this;
    }
    
    /**
     * Returns as `true` if the resource has been successfully deleted.
     */
    @JsonProperty("deleted")
    public Boolean deleted;

    public ExportRetrieveResponseBody withDeleted(Boolean deleted) {
        this.deleted = deleted;
        return this;
    }
    
    /**
     * The URL for the generated export file.
     */
    @JsonProperty("s3Url")
    public String s3Url;

    public ExportRetrieveResponseBody withS3Url(String s3Url) {
        this.s3Url = s3Url;
        return this;
    }
    
    /**
     * The state of the export file, which can be `in_progress`, `failed` or `succeeded`.
     */
    @JsonProperty("state")
    public State state;

    public ExportRetrieveResponseBody withState(State state) {
        this.state = state;
        return this;
    }
    
    /**
     * The export file type, which can be `all`, `failures` or `successes`.
     */
    @JsonProperty("type")
    public ExportRetrieveType type;

    public ExportRetrieveResponseBody withType(ExportRetrieveType type) {
        this.type = type;
        return this;
    }
    
    /**
     * Unique identifier prefixed with `upl_`.
     */
    @JsonProperty("uploadId")
    public String uploadId;

    public ExportRetrieveResponseBody withUploadId(String uploadId) {
        this.uploadId = uploadId;
        return this;
    }
    
    public ExportRetrieveResponseBody(@JsonProperty("id") String id, @JsonProperty("dateCreated") OffsetDateTime dateCreated, @JsonProperty("dateModified") OffsetDateTime dateModified, @JsonProperty("deleted") Boolean deleted, @JsonProperty("s3Url") String s3Url, @JsonProperty("state") State state, @JsonProperty("type") ExportRetrieveType type, @JsonProperty("uploadId") String uploadId) {
        this.id = id;
        this.dateCreated = dateCreated;
        this.dateModified = dateModified;
        this.deleted = deleted;
        this.s3Url = s3Url;
        this.state = state;
        this.type = type;
        this.uploadId = uploadId;
  }
}
