/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ExportRetrieveType - The export file type, which can be `all`, `failures` or `successes`.
 */
public enum ExportRetrieveType {
    ALL("all"),
    FAILURES("failures"),
    SUCCESSES("successes");

    @JsonValue
    public final String value;

    private ExportRetrieveType(String value) {
        this.value = value;
    }
}
