/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;


public class LetterCancelRequest {
    /**
     * id of the letter
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ltr_id")
    public String ltrId;

    public LetterCancelRequest withLtrId(String ltrId) {
        this.ltrId = ltrId;
        return this;
    }
    
    public LetterCancelRequest(@JsonProperty("ltr_id") String ltrId) {
        this.ltrId = ltrId;
  }
}
