/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;


public class LinkUpdateRequest {
    /**
     * Unique identifier for a link.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=link_id")
    public String linkId;

    public LinkUpdateRequest withLinkId(String linkId) {
        this.linkId = linkId;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public org.openapis.openapi.models.shared.LinkSingle linkSingle;

    public LinkUpdateRequest withLinkSingle(org.openapis.openapi.models.shared.LinkSingle linkSingle) {
        this.linkSingle = linkSingle;
        return this;
    }
    
    public LinkUpdateRequest(@JsonProperty("link_id") String linkId, @JsonProperty("link_single") org.openapis.openapi.models.shared.LinkSingle linkSingle) {
        this.linkId = linkId;
        this.linkSingle = linkSingle;
  }
}
