/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;


public class PostcardRetrieveRequest {
    /**
     * id of the postcard
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=psc_id")
    public String pscId;

    public PostcardRetrieveRequest withPscId(String pscId) {
        this.pscId = pscId;
        return this;
    }
    
    public PostcardRetrieveRequest(@JsonProperty("psc_id") String pscId) {
        this.pscId = pscId;
  }
}
