/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Type {
    ALL("all"),
    FAILURES("failures"),
    SUCCESSES("successes");

    @JsonValue
    public final String value;

    private Type(String value) {
        this.value = value;
    }
}
